### ISSUE TITLE
打包报错

### ISSUE THREAD

**Issue by cf48rty** [ChinaRan0/Simulate-fishing#1]
Traceback (most recent call last):
  File "模拟.py", line 113, in <module>
  File "subprocess.py", line 829, in __init__
  File "subprocess.py", line 1252, in _get_handles
OSError: [WinError 6] 句柄无效。

**Comment by ChinaRan0** [comment]
代码已更新，重新下载试一下。

**Comment by cf48rty** [comment]
Traceback (most recent call last):
  File "模拟.py", line 113, in <module>
  File "subprocess.py", line 424, in check_output
  File "subprocess.py", line 505, in run
  File "subprocess.py", line 829, in __init__
  File "subprocess.py", line 1252, in _get_handles
OSError: [WinError 6] 句柄无效。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "模拟.py", line 123, in <module>
NameError: name 'output' is not defined
  运行后错误更多了

**Comment by ChinaRan0** [comment]
你的Python版本号是多少

**Comment by cf48rty** [comment]
Python 3.9.7

**Comment by ChinaRan0** [comment]
请尝试更新pyinstaller
```python
pip install --upgrade pyinstaller
```
我的版本pyinstaller v6.2.0可以正常打包，是没有问题的。

**Comment by greaktang** [comment]
使用pycharm运行app.py时提示“以一种访问权限不允许的方式做了一个访问套接字的尝试”。
![Uploading 微信截图_20231214194715.png…]()
